version: '3.8'

services:
  # 数据库服务
  db:
    image: mongo:latest
    container_name: stock-mongodb
    restart: always
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 后端 API 服务
  backend:
    build: ./backend
    container_name: stock-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/make_a_million
    depends_on:
      - db

  # 前端 Web 服务
  frontend:
    build: .
    container_name: stock-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
